"""Render audit report from completed, separately saved production/rescore outputs."""
import csv,json,hashlib
from pathlib import Path
import numpy as np
O=Path(__file__).resolve().parent;R=O/'rescore'
read=lambda n:list(csv.DictReader((R/n).open()))
f=lambda v:float(v)
def fmt(v,n=3):return f'{float(v):.{n}f}'
def tab(cols,rows):return '\n'.join(['| '+' | '.join(cols)+' |','|'+'|'.join(['---']*len(cols))+'|',*['| '+' | '.join(map(str,r))+' |' for r in rows]])
a=read('associations.csv');s=read('model_scores_ranks.csv');t=read('truths_quantiles_floors.csv');v=read('production_validation.csv');c=read('coverage_summary.csv');conv=read('score_convergence.csv');qc=read('convergence.csv');success=json.loads((R/'SUCCESS.json').read_text());prod=json.loads((O/'SUCCESS.json').read_text());audit=json.loads((R/'forecast_audit.json').read_text());roster=json.loads((R/'roster.json').read_text())
planhash=(O/'PLAN.sha256').read_text().strip();parts=[]
parts.append('# Starsim fixed-state production and retrospective rescore\n\n**Completed: 16,000 branches, 4,000 independent continuation sets, 1,000 per world, four paired arms per set.** All production and rescore validation passed. Original forecasts, prior audit/failure artifacts and manuscript inputs were preserved. No model calls, cloud spending or remote writes were used. This is a retrospective fixed-hidden-state rescore, not a newly elicited benchmark and not the distribution conditional only on the displayed report.\n')
parts.append('## Main numerical changes\n\nScores below are normalized excess five-quantile CRPS approximations (lower is better). The paper constants remain **C40=200 and C60=300 people**. Panel membership is complete-item based, exactly as in the paper; planned repetition completeness is audited separately. Every before/after comparison uses the same models and forecasts.\n')
rows=[]
for group in ['cont_uncond','cont_int_c25','cont_int_c50','cont_int_c90','interventional_pooled','all_continuous']:
 rs=[r for r in s if r['group']==group and r['horizon']=='pooled'];rows.append([group,len(rs),fmt(np.mean([f(r['old_excess']) for r in rs])),fmt(np.mean([f(r['new_excess']) for r in rs])),fmt(np.mean([f(r['delta']) for r in rs])),fmt(max(abs(f(r['rank_move'])) for r in rs),1)])
parts.append(tab(['Panel','Models','Original mean','Fixed-state mean','Change','Largest rank move'],rows))
parts.append('\nPositive correlations below mean that higher ECI/ForecastBench overall accompanies better forecasting: −Spearman(external score, excess loss). For combined theta, higher is better and no sign reversal is applied. The first interval resamples models, holding truth estimates fixed; the second resamples continuation seeds within each world, holding models fixed. **These are distinct sources of uncertainty, not a joint confidence interval.** Some replay correlation intervals collapse because resampling does not change model ranks; this does not imply certainty about a population association.\n')
rows=[]
for group in ['cont_uncond','interventional_pooled','combined_six','combined_ten']:
 for metric in ['eci','fb_overall']:
  r=next(r for r in a if r['group']==group and r['horizon']=='pooled' and r['against']==metric)
  rows.append([group,metric,r['n'],fmt(r['old_skill_rho'],2),fmt(r['new_skill_rho'],2),f"[{fmt(r['new_panel_lo'],2)}, {fmt(r['new_panel_hi'],2)}]",f"[{fmt(r['new_replay_lo'],2)}, {fmt(r['new_replay_hi'],2)}]"])
parts.append(tab(['Panel','External score','n','Original rho','New rho','95% model-panel interval','95% replay interval'],rows))
parts.append('\n[associations.csv](rescore/associations.csv) gives every coverage/horizon, original intervals, changes and their separate uncertainty intervals. [panels.json](rescore/panels.json) lists each actual model panel, including the smaller matched ForecastBench panel. Combined six/ten-cell fits keep other engines and Starsim binary cells unchanged. They are sensitivity results for the existing combined score, not a claim that all benchmark components have been repaired.\n')
parts.append('## Model scores and ranks\n\nRanks are within each complete panel, 1=lowest excess. “—” denotes exclusion from the complete interventional panel, not a zero score. Full horizon/coverage tables and replay score/rank intervals are in [model_scores_ranks.csv](rescore/model_scores_ranks.csv); individual model-item scores and ranks are in [item_scores.csv](rescore/item_scores.csv) and [item_ranks.csv](rescore/item_ranks.csv).\n')
rows=[]
for m in sorted(roster,key=lambda x:-x['eci']):
 row=[m['name']]
 for group in ['cont_uncond','interventional_pooled']:
  rs=[r for r in s if r['group']==group and r['horizon']=='pooled' and r['model']==m['openrouter_id']]
  if rs:
   r=rs[0];row.extend([f"{fmt(r['old_excess'])} → {fmt(r['new_excess'])}",f"{fmt(r['old_rank'],0)} → {fmt(r['new_rank'],0)}"])
  else:row.extend(['—','—'])
 rows.append(row)
parts.append(tab(['Model','Baseline score','Baseline rank','Vaccine pooled score','Vaccine pooled rank'],rows))
parts.append('\n[Combined model scores and ranks](rescore/combined_scores_ranks.csv) include replay intervals. No ranking, correlation or desirable result was used to choose N, seeds, sample retention or precision cutoffs.\n\n![Original versus fixed-state scores](rescore/score_comparison.png)\n')
parts.append('## Truths, floors and precision\n\nAll 32 item distributions have exactly 1,000 samples. Outcomes count infections after the end of day 20, using the exact displayed cumulative baseline. Day-40 and day-60 outcomes come from the same branch. The new truths obey 0≤Y40≤Y60≤5000−C20. No truth or forecast clipping was applied. The table shows day 60; the linked CSV contains both horizons, all five quantiles, point changes, floor changes, bootstrap intervals and distribution-free order-statistic intervals in people.\n')
rows=[]
for r in t:
 if r['horizon']=='60':rows.append([r['source'],r['world'],f"{fmt(r['p50_old'],0)} → {fmt(r['p50_new'],0)}",f"{fmt(r['old_floor'],2)} → {fmt(r['new_floor'],2)}",f"[{fmt(r['p50_order_lo'],0)}, {fmt(r['p50_order_hi'],0)}]"])
parts.append(tab(['Condition','World','Median: old → new','Floor: old → new','New median 95% order interval'],rows))
parts.append('\n[Full truths/quantiles/floors](rescore/truths_quantiles_floors.csv). The empirical floor minimizes the same five pinball losses used by the actual paper scorer; it is not a full-distribution CRPS oracle. A narrower fixed-state distribution is expected because it removes variation over different pre-day20 states. Changes in excess therefore reflect both changes in outcomes and in the floor; they should not be interpreted as newly demonstrated model deterioration on an unchanged statistical target.\n\n![Fixed-state day-60 distributions](rescore/fixed_state_cdfs.png)\n')
rows=[]
for n in [100,300,500,1000]:
 rs=[r for r in conv if int(r['N'])==n and r['horizon']=='pooled' and r['group'] in ['cont_uncond','interventional_pooled']];qs=[r for r in qc if int(r['N'])==n]
 rows.append([n,fmt(max(f(r['max_quantile_delta_final']) for r in qs),0),fmt(max(abs(f(r['floor_delta_final'])) for r in qs),3),fmt(max(f(r['max_score_delta_final']) for r in rs),4)])
parts.append('Prespecified prefixes, compared with the final N=1000 estimate:\n\n'+tab(['N','Largest quantile difference (people)','Largest floor difference (people)','Largest pooled model-score difference'],rows))
opt=read('floor_split_diagnostic.csv')
parts.append(f"\nThese nested-prefix comparisons are convergence diagnostics, not independent validation samples or a stopping rule. [convergence.csv](rescore/convergence.csv) and [score_convergence.csv](rescore/score_convergence.csv) contain every item/panel; final split-half KS distances are also recorded. The two-fold 500/500 floor diagnostic has mean train-to-test optimism {fmt(np.mean([f(r['half_optimism']) for r in opt]),3)} people, maximum {fmt(max(f(r['half_optimism']) for r in opt),3)}; it diagnoses empirical quantile estimation, not a correction applied to the paper score. [Floor split diagnostic](rescore/floor_split_diagnostic.csv).\n")
parts.append('Replay bootstrap uses **1,000 resamples**, selecting continuation indices independently within each world and sharing each index vector across coverage arms and horizons. Each resample recomputes truth quantiles, floors, scores, rankings and associations. Original truth estimates are held fixed when reporting changes; the intervals do not cover bias or Monte Carlo error in the old matched-seed target. Model-panel bootstrap uses **2,000 paired resamples of model identities** for before/after correlations, with truth held fixed. Models are an observed convenience panel, not a random sample of all possible models; the resampling interpretation assumes exchangeability. Combined-score model intervals resample fitted theta values, following the paper convention, without refitting a different model panel; replay intervals do refit the fixed panel. Neither interval resamples the four worlds, elicitation calls, external benchmark measurements or latent anchor states.\n\nAt N=1000, pointwise CDF standard error is at most 1.58 percentage points; approximate 95% margin at the median is ±3.10 pp, and at a decile ±1.86 pp. A conservative uniform 95% DKW bound is ±4.29 pp for one distribution, or ±5.98 pp simultaneously over all 32 by a union bound. These probability-scale bounds are not infection-count quantile error guarantees. Ties make order-statistic intervals conservative.\n')
parts.append('## Forecast coverage and retained limitations\n')
rows=[]
for source in sorted({r['source'] for r in c}):
 rs=[r for r in c if r['source']==source];rows.append([source,sum(int(r['actual_calls']) for r in rs),sum(int(r['expected_calls']) for r in rs),sum(int(r['expected_items'])-int(r['items_with_answer']) for r in rs),sum(int(r['cells_below_planned_reps']) for r in rs)])
parts.append(tab(['Source','Saved calls','Planned calls','Wholly missing model-items','Cells below planned reps'],rows))
parts.append(f"\nThere are **{len(audit['duplicate_rep_keys'])} duplicate repetition keys** and **{len(audit['repeated_answer_cells'])} cells with repeated answer values**. Repeated values are not automatically duplicate calls or errors. The actual scorer takes coordinate-wise medians over every saved row, without deduplicating values or demanding all planned repetitions. We retained this behavior. No responses were imputed or newly elicited. [Forecast audit](rescore/forecast_audit.json), [all cell/repetition records](rescore/forecast_coverage.csv), [coverage by model/source](rescore/coverage_summary.csv).\n")
parts.append('DeepSeek V4 Flash has missing interventional items and is excluded from complete pooled intervention correlations/ranks; its available-item score remains in the paper-format long table. Models with every item answered but fewer repetitions remain eligible, including the Kimi K2 completion pattern. Unequal repetitions affect the median estimates and are not captured by replay or model-panel bootstrap intervals. Binary scores are retained unchanged; this continuous fixed-state production does not repair binary truth construction.\n')
parts.append('## Implementation, provenance and cost\n\nThe production runner imports the corrected, validated execution helper and retains its float-coverage, independent recipient-ID oracle, nonempty-uptake, exact timing, susceptibility, history, latent recovery, conservation and support assertions. Coverage is Bernoulli uptake among all 5,000 living agents, including infected/recovered agents, with 0.95 leaky efficacy. It is not exact-size vaccination or susceptible-only selection. Each seed set branches into 0%, 25%, 50%, 90% arms with common distribution roots; day-21 networks match and vaccinated sets strictly nest. All 40,000 distribution-root hashes are distinct across independent world/replicate/stream combinations. Distinct pseudo-random roots and prior fresh-process/daywise tests support the implementation; finite samples cannot prove statistical independence.\n')
rows=[]
for cov in ['0','0.25','0.5','0.9']:
 rs=[r for r in v if float(r['coverage'])==float(cov)]
 rows.append([cov,4000,min(int(r['vaccinated_min']) for r in rs),max(int(r['vaccinated_max']) for r in rs),fmt(np.mean([f(r['vaccinated_mean']) for r in rs]),2)])
parts.append(tab(['Coverage','Branches','Minimum vaccinated','Maximum vaccinated','Mean vaccinated'],rows)+'\n\n[Full world/coverage validation counts](rescore/production_validation.csv).')
parts.append(f"Production passed **{success['production_checks']:,} recorded helper assertions** (not independent statistical observations), plus pairing and checkpoint checks. Every checkpoint was re-read and validated in the separate scoring process; daily infection sums, support, sample counts and unchanged pre-day20 infection histories were checked again. Input hashes were verified before and after production and analysis, and 53 manuscript files were fingerprinted and preserved. The original paper scoring path reproduced all **576 saved rows exactly at its six-significant-digit serialization** before new truth files were substituted in memory. [Production result](SUCCESS.json), [rescore result](rescore/SUCCESS.json), [input hashes](rescore/input_hashes.json), [checkpoint hashes](checkpoint_hashes.json).\n")
parts.append(f"Frozen plan SHA-256: `{planhash}`. [PLAN.json](PLAN.json) records all 4,000 seeds, worlds, arms, horizons, fixed sample size, analysis rules and input hashes before new scores were inspected. Production seed entropy is `[20260924,16000,world_index,rep]`, separate from the smoke-suite schedule. Existing serialized anchors and pre-drawn recovery states remain fixed. Starsim 3.3.4 / NumPy 2.5.2 / Python 3.13.7 generated trajectories; the separate scoring environment uses the paper's imported code.\n")
parts.append(f"Measured resumed production loop elapsed time (excludes first attempt and diagnostic pause): **{prod['elapsed_s_this_invocation']/60:.2f} minutes**; per-checkpoint work totals {success['checkpoint_elapsed_sum_s']/60:.2f} minutes. Parent peak RSS (substantially higher than the smoke-suite estimate; cause not profiled): {prod['max_rss_bytes']/1024**2:.1f} MiB. Rescore elapsed: **{success['elapsed_s']/60:.2f} minutes**. Startup/import and report preparation are additional; these are measured stage timings, not inferred API latencies. Checkpoints occupy {sum(p.stat().st_size for p in (O/'checkpoints').glob('*.gz'))/1024**2:.2f} MiB compressed. Full branch simulators were not saved. Paid model/cloud cost: **$0**. Diagnostic recomputed scales would be {success['C_if_reestimated_diagnostic_only']}; they were not used, because changing normalization would confound the before/after comparison.\n")
from datetime import datetime
frozen=json.loads((O/'PLAN.json').read_text())['frozen_utc']
wall=(datetime.fromisoformat(prod['completed_utc'].replace('Z','+00:00'))-datetime.fromisoformat(frozen.replace('Z','+00:00'))).total_seconds()/60
parts.append(f'Frozen plan to production completion wall time was **{wall:.2f} minutes**, including launch/import overhead and the diagnostic interruption. The first attempt reached at least 846.02 seconds before stopping; its final elapsed time was not recorded, so the valid-checkpoint work sum and resumed-loop timing above are the exact available processing measurements.')
parts.append('Atomic checkpoints store each completed four-arm seed set. Resume checks job identity and frozen plan and skips existing sets. Any incomplete set is recomputed deterministically. This run resumed after the documented assertion-only correction below, skipping 2,245 completed sets and recomputing the incomplete w2/245 set. There are 16,000 unique validated output branches and 16,004 starts in total: the failed attempt completed three unsaved arms and partially advanced one arm. No additional independent seeds were sampled.\n')
parts.append('## Preserved production failure and checker-only amendment\n\nThe first invocation stopped at w2/rep245/c90 because its independently predicted recipients differed by one agent. The simulator used the intended float64 probability 0.9. The checker compared float32 uniforms with a Python scalar, which NumPy treated as a weak scalar and rounded to float32. A uniform exactly 0.8999999761581421 was therefore excluded by the old checker but included by the simulator. This was an oracle error, not the previous integer-zero vaccine bug. Array-only diagnosis advanced no simulator steps.\n\nThe amendment uses an explicit NumPy float64 threshold; boundary-value tests for every coverage include a negative control that fails under the old 90% comparison. No seeds, sample size, simulator behavior, coverage values, previous successful outcomes, score rules or normalization changed. The failing set then passed with 4,492 vaccinated agents, matching the corrected independent prediction. The original code, frozen plan, log and failure JSON remain preserved. [Diagnosis](threshold_diagnosis.json), [frozen amendment](ORACLE_AMENDMENT.json), [corrected checker](/Users/elsehow/Projects/starsim-audit-20260923/production_v1/oracle_precision.py:16), [resume code](resume.py). A separate array-only audit regenerated all 16,000 recipient sets and verified their saved hashes/counts, without invoking simulator steps: [uptake verification](UPTAKE_VERIFICATION.json).\n')
parts.append('The scoring environment emitted NumPy matmul divide/overflow/invalid warnings, preserved in rescore.log. All available bootstrap scores were finite. Independent non-BLAS summation matched every bootstrap score and combined-score interval exactly; checks against the original scorer and iterative combined fitter differed by at most 1.6×10^-14. No corresponding numerical error was found, and the library-warning cause was not established. [Numerical verification](NUMERIC_VERIFICATION.json), [verification code](verify_numeric.py).')
parts.append('## Proposed manuscript implications — not applied\n\n1. Replace the continuous ±15% seed-pooling description with the exact day-20 snapshot, 1,000 future continuation roots, paired-arm procedure, random vaccination semantics and validated displayed-count subtraction. Keep the historical design description distinguishable from the retrospective repair. [Current design](/Users/elsehow/Projects/iclr-score-refresh/paper/sections/06_starsim.tex:14).\n2. Update continuous truths/floors, per-model and per-item tables, coverage/horizon figures, ECI/ForecastBench intervals and combined-score figures together if these results are accepted. Review abstract/discussion claims that cite their previous associations. Preserve explicit panels and the missing-repetition caveat. [Current results](/Users/elsehow/Projects/iclr-score-refresh/paper/sections/06_starsim.tex:34), [validation](/Users/elsehow/Projects/iclr-score-refresh/paper/sections/07_validation.tex:6).\n3. Say that 200/300 are retained historical reference scales. They are no longer the median replay-range scales of this new distribution. Either retain them transparently for comparison or separately authorize a consistently relabeled normalization; do not quietly present the old constants as freshly estimated. [Current scoring description](/Users/elsehow/Projects/iclr-score-refresh/paper/sections/06_starsim.tex:28).\n4. State the information limitation prominently: the fixed snapshot contains agent-level/network/disease/prognosis information not shown in the report. This target is P(Y | fixed full state, intervention), not automatically P(Y | displayed aggregate report, intervention). Proper report-only conditioning requires a distribution over compatible latent states. Merely narrowing cumulative-count windows does not supply that distribution.\n5. Describe the outcome scores as interventional forecasting performance. They mix baseline epidemic prediction with response to vaccination and **do not isolate effect-estimation skill**. Shared randomness improves paired simulation comparisons but does not change what the elicited outcome score measures.\n\n**Recommended next decision:** review and accept or reject this explicitly labeled retrospective fixed-state analysis for the paper before changing manuscript outputs. The production implementation is validated and sample size was fixed on precision grounds. Accepting the numerical rescore does not resolve the report-only versus hidden-state information convention. A prospective redesign or re-elicitation should be a separate decision; nothing here authorizes new paid calls.\n')
parts.append('## Reproducible commands and files\n\n```sh\n# Already executed: freeze once, then production (resume-safe)\nsh /Users/elsehow/Projects/starsim-audit-20260923/production_v1/run.sh --freeze\nsh /Users/elsehow/Projects/starsim-audit-20260923/production_v1/run.sh\n# Recorded checker-only amendment; resume with this entry point\nsh /Users/elsehow/Projects/starsim-audit-20260923/production_v1/resume.sh\n# Separate offline analysis; uses the actual paper score_all(C)\nsh /Users/elsehow/Projects/starsim-audit-20260923/production_v1/rescore.sh\n```\n\nThe freeze command refuses to overwrite the existing plan. The initial run.sh entry point intentionally preserves the old checker; use resume.sh to apply the recorded assertion-only precision amendment when continuing/reproducing production. Preserve these outputs when reproducing in a versioned directory. [Production/checkpoint code](/Users/elsehow/Projects/starsim-audit-20260923/production_v1/production.py:30), [corrected execution helper](/Users/elsehow/Projects/starsim-audit-20260923/corrected_smoke/validate.py:46), [RNG reseeding helper](/Users/elsehow/Projects/starsim-audit-20260923/smoke/smoke.py:94), [actual scorer invocation](/Users/elsehow/Projects/starsim-audit-20260923/production_v1/rescore.py:80), [paired replay bootstrap](/Users/elsehow/Projects/starsim-audit-20260923/production_v1/rescore.py:84), [model-panel bootstrap](/Users/elsehow/Projects/starsim-audit-20260923/production_v1/rescore.py:124), [paper scorer](/Users/elsehow/Projects/iclr-score-refresh/paper/data/starsim/scripts/build_excess.py:48), [supplementary diagnostics](supplement.py).\n\nFile-only supplement/report commands use `uv run --offline --no-project --python /Users/elsehow/Projects/iclr-score-refresh/venv/bin/python --no-managed-python python` followed by the absolute path to `supplement.py` or `build_report.py`, with UV_CACHE_DIR/MPLCONFIGDIR set under this audit directory as in rescore.sh. No manuscript files were generated or installed.\n')
(O/'REPORT.md').write_text('\n\n'.join(parts));print('Wrote report',O/'REPORT.md')
