"""Micropolis city-sim runner + serializer into the fbsim-core turn-major schema."""

import json
import subprocess
from collections import defaultdict
from pathlib import Path
from typing import Any

from . import module_globals as g


def _load_jsonl(file_path: Path) -> list[dict]:
    """Load a JSONL file and return a list of dicts."""
    with open(file_path, "r") as f:
        return [json.loads(line) for line in f if line.strip()]


class CitySimulation:
    """Class to run a Micropolis city simulation and collect metrics."""

    def __init__(self, city_name: str, seed: int, disasters: bool = False):
        self.city_name = city_name
        self.seed = seed
        self.disasters = disasters
        self.log_data: list[dict] | None = None
        self.events_data: list[dict] | None = None
        self.nturns: int | None = None

    def get_id_str(self) -> str:
        """Get a unique string identifier for this simulation."""
        return f"{self.city_name}_{'disasters' if self.disasters else 'nodisasters'}_seed{self.seed}"

    def describe(self) -> dict[str, Any]:
        return {"name": self.city_name, "seed": self.seed, "disasters": self.disasters}

    def run(self, nturns: int, quiet: bool = True) -> None:
        """Run the simulation for a given number of turns."""
        args = [
            "--city",
            self.city_name,
            "--seed",
            str(self.seed),
            "--turns",
            str(nturns),
            "--output-base-dir",
            g.RUNS_DIR,
        ]
        if self.disasters:
            args.append("--disasters")
        else:
            args.append("--no-disasters")

        result = subprocess.run(
            ["pnpm", "run", "run-sim", *args],
            cwd=g.MICROPOLIS_APP_PATH,
            check=False,
            stdout=subprocess.DEVNULL if quiet else None,
            stderr=subprocess.DEVNULL if quiet else None,
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"micropolis run-sim failed with exit code {result.returncode}"
            )

    def get_data_file_path(self, prefix: str, ext="jsonl") -> Path:
        """Get the path to the data file generated by the simulation.
        Common prefixes are "log", "events", and
        "worldreport-{LABEL}-T{TURN}"."""
        disasters_str = "disasters" if self.disasters else "nodisasters"
        filename = f"{prefix}-seed{self.seed}-{disasters_str}.{ext}"
        return g.RUNS_DIR / self.city_name / filename

    def get_plot_path(self, prefix: str = "plot") -> Path:
        """Where this run's plot is written, alongside its log/events files."""
        return self.get_data_file_path(prefix, ext="png")

    def load_from_disk(self) -> None:
        """Load the simulation data from disk and return it in the core schema."""
        log_path = self.get_data_file_path("log")
        events_path = self.get_data_file_path("events")

        if not log_path.exists():
            raise FileNotFoundError(f"Simulation log file not found: {log_path}")
        if not events_path.exists():
            raise FileNotFoundError(f"Simulation events file not found: {events_path}")

        self.log_data = _load_jsonl(log_path)
        self.events_data = _load_jsonl(events_path)
        self.nturns = len(self.log_data)

    def run_if_needed_and_load(self, nturns: int, quiet: bool = True) -> None:
        """Load cached data from disk, re-running the sim only if it's missing or short.

        A cached run longer than nturns is reused as-is (callers index into
        log_data, so extra turns are harmless).
        """
        try:
            self.load_from_disk()
        except FileNotFoundError:
            pass
        else:
            if self.nturns is not None and self.nturns >= nturns:
                return

        self.run(nturns=nturns, quiet=quiet)
        self.load_from_disk()


def turn_of(row: dict) -> int:
    """The turn a log or event row falls on."""
    return row["tick"] // g.TICKS_PER_TURN


def to_world(sims: dict[str, CitySimulation]) -> dict:
    """Assemble game_data in the core TURN-MAJOR schema:
    time_series[metric][turn][region_id] = value.
    """
    ts = {m: defaultdict(dict) for m in g.METRICS}
    for sim_id, (name, sim) in enumerate(sims.items()):
        if sim.log_data is None:
            raise ValueError(f"Simulation {name} has no log_data")
        for line in sim.log_data:
            turn = turn_of(line)
            for metric in g.METRICS:
                ts[metric][str(turn)][str(sim_id)] = line[metric]
    return {
        "time_series": ts,
        "civilizations": {
            str(sim_id): {"name": name, "nation_id": str(sim_id)}
            for sim_id, (name, _) in enumerate(sims.items())
        },
    }
