"""Second pass on top of build_excess.py: appendix tables in the paper's layout, validation-table rows
(ECI seed 0, matching the published figures; ForecastBench seed 2026; figures.rho_ci), p-values, the
horizon figure in raw units (people), per-set item-difficulty summaries. Reads build_excess outputs."""
import argparse, csv, json, statistics, sys
from collections import defaultdict
from pathlib import Path
import numpy as np
from scipy.stats import spearmanr
from paths import analysis_modules
ANALYSIS_ROOT, bt, fg = analysis_modules()
import matplotlib.pyplot as plt
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--analysis-root', type=Path, default=Path.cwd())
parser.add_argument('--out', type=Path, required=True, help='Existing build_excess.py output directory')
args = parser.parse_args()
OUT = args.out.resolve()
roster = bt.load_roster(); ECI = {m.openrouter_id: m.eci for m in roster}; FB = {m.openrouter_id: m.fb_overall for m in roster}
long = list(csv.DictReader(open(OUT / "starsim_excess_long.csv")))
for r in long:
    for k in ("eci", "excess", "crps", "floor", "excess_raw", "cost_usd", "excess_bits", "excess_brier"):
        if r.get(k) not in (None, ""): r[k] = float(r[k])
    r["complete"] = r["complete"] == "True"; r["n_calls"] = int(r["n_calls"]) if r["n_calls"] else 0
cells = defaultdict(dict)
for r in long: cells[(r["question_type"], r["condition"], r["rung"], r["horizon"])][r["model"]] = r
def pts(qtype, cond, rung, h="pooled", against="eci"):
    out = []
    for m, r in cells[(qtype, cond, rung, h)].items():
        if r.get("excess") in (None, ""): continue
        x = ECI[m] if against == "eci" else FB[m]
        if x is None: continue
        out.append((m, float(x), r["excess"], r["complete"]))
    return sorted(out, key=lambda t: t[1])
def stats(qtype, cond, rung, against="eci"):
    p = pts(qtype, cond, rung, against=against); rho, lo, hi, n = fg.rho_ci(p, seed=0 if against == "eci" else 2026)
    full = [q for q in p if q[3]]; pv = float(spearmanr([q[1] for q in full], [q[2] for q in full]).pvalue)
    return dict(rho=rho, lo=lo, hi=hi, n=n, p=pv)
ROWS = [("Excess CRPS, interventional", ("continuous", "interventional", "pooled(c25,c50,c90)")),
        ("Excess bits, binary", ("binary", "unconditional", "-")), ("Excess CRPS, continuous", ("continuous", "unconditional", "-"))]
val = {}
for label, key in ROWS:
    val[label] = dict(eci=stats(*key), fb=stats(*key, against="fb"))
def fmt_row(label, s, first):
    # sign flipped so that positive = more capable models score better (excess is lower-is-better)
    rho, lo, hi = -s["rho"], -s["hi"], -s["lo"]; p = "$<$0.001" if s["p"] < 0.001 else f"{s['p']:.3f}"
    lead = "\\multirow{3}{*}{Starsim}" if first else ""
    return f"{lead} & {label} & {s['n']} & ${rho:.2f}$ & $[{lo:.2f}, {hi:.2f}]$ & {p}"
snip = {"validation_table.tex": [], "validation_table_main.tex": [], "validation_table_forecastbench.tex": []}
for i, (label, key) in enumerate(ROWS):
    snip["validation_table.tex"].append(fmt_row(label, val[label]["eci"], i == 0) + " & -- \\\\")
    snip["validation_table_main.tex"].append(fmt_row(label, val[label]["eci"], i == 0) + " \\\\")
    snip["validation_table_forecastbench.tex"].append(fmt_row(label, val[label]["fb"], i == 0) + " & -- \\\\")
(OUT / "validation_rows.json").write_text(json.dumps({"stats": val, "rows": snip}, indent=1))

# ---- appendix tables in the paper's layout ------------------------------------------------------------
def f3(x):
    if x is None or x == "": return "--"
    s = f"{x:.3f}"; return s.replace("-", "$-$")
order = sorted(roster, key=lambda m: -m.eci); DS = "deepseek/deepseek-v4-flash-0731"
def name(m): return fg.SHORT.get(m.openrouter_id, m.name) + ("$^{\\dagger}$" if m.openrouter_id == DS else "")
def cell(qtype, cond, rung, h, m): r = cells[(qtype, cond, rung, h)].get(m); return r["excess"] if r and r.get("excess") not in (None, "") else None
L = ["% Generated by build_excess_extra.py (Nick, 2026-09-17) from starsim_excess_long.csv; do not edit by hand.",
     "% Starsim per model, horizons pooled, EXCESS convention: binary = excess bits (KL(P*||f), f clipped to [.001,.999]; every P* is 0, 1 or within 0.03 of it), continuous = excess CRPS (five elicited quantiles p10..p90 vs the matched replay seeds, minus the floor) / C_h with C_40 = 200 and C_60 = 300 people. Lower is better. Calls and cost sum the five sets, each call once. Dagger = DeepSeek V4 Flash, 21 of 24 interventional items.",
     "\\setlength{\\tabcolsep}{2.2pt}", "\\begin{tabular}{lrrrrrrrrrrr}", "\\toprule",
     "Model & ECI & Binary & Cont. & \\multicolumn{4}{c}{Interventional excess CRPS, by coverage} & Binary & Hold & Calls & Cost \\\\",
     "\\cmidrule(lr){5-8}", " & & bits & excess & 25\\% & 50\\% & 90\\% & pooled & c90 bits & bits & & (\\$) \\\\", "\\midrule"]
for m in order:
    mid = m.openrouter_id
    calls = sum(cells[k][mid]["n_calls"] for k in (("binary", "unconditional", "-", "pooled"), ("continuous", "unconditional", "-", "pooled"), ("continuous", "interventional", "pooled(c25,c50,c90)", "pooled"),
                                                   ("binary", "interventional", "c90", "pooled"), ("binary", "interventional", "hold", "pooled")) if mid in cells[k])
    cost = sum(cells[k][mid]["cost_usd"] for k in (("binary", "unconditional", "-", "pooled"), ("continuous", "unconditional", "-", "pooled"), ("continuous", "interventional", "pooled(c25,c50,c90)", "pooled"),
                                                  ("binary", "interventional", "c90", "pooled"), ("binary", "interventional", "hold", "pooled")) if mid in cells[k])
    L.append(f"{name(m)} & {m.eci:.1f} & {f3(cell('binary','unconditional','-','pooled',mid))} & {f3(cell('continuous','unconditional','-','pooled',mid))} & "
             f"{f3(cell('continuous','interventional','c25','pooled',mid))} & {f3(cell('continuous','interventional','c50','pooled',mid))} & {f3(cell('continuous','interventional','c90','pooled',mid))} & "
             f"{f3(cell('continuous','interventional','pooled(c25,c50,c90)','pooled',mid))} & {f3(cell('binary','interventional','c90','pooled',mid))} & {f3(cell('binary','interventional','hold','pooled',mid))} & {calls} & {cost:.2f} \\\\")
L += ["\\bottomrule", "\\end{tabular}"]; (OUT / "starsim_models.tex").write_text("\n".join(L) + "\n")
L = ["% Generated by build_excess_extra.py (Nick, 2026-09-17) from starsim_excess_long.csv; do not edit by hand.",
     "% Starsim by horizon (day 40, day 60), EXCESS convention as in starsim_models.tex; lower is better.",
     "\\setlength{\\tabcolsep}{2.2pt}", "\\begin{tabular}{lrrrrrrrrrrr}", "\\toprule",
     "Model & ECI & \\multicolumn{2}{c}{Binary bits} & \\multicolumn{2}{c}{Cont. excess} & \\multicolumn{2}{c}{Interv. excess} & \\multicolumn{2}{c}{Binary c90 bits} & \\multicolumn{2}{c}{Hold bits} \\\\",
     "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}\\cmidrule(lr){9-10}\\cmidrule(lr){11-12}", " & & d40 & d60 & d40 & d60 & d40 & d60 & d40 & d60 & d40 & d60 \\\\", "\\midrule"]
for m in order:
    mid = m.openrouter_id; c = []
    for key in (("binary", "unconditional", "-"), ("continuous", "unconditional", "-"), ("continuous", "interventional", "pooled(c25,c50,c90)"), ("binary", "interventional", "c90"), ("binary", "interventional", "hold")):
        c += [f3(cell(*key, "40", mid)), f3(cell(*key, "60", mid))]
    L.append(f"{name(m)} & {m.eci:.1f} & " + " & ".join(c) + " \\\\")
L += ["\\bottomrule", "\\end{tabular}"]; (OUT / "starsim_horizon.tex").write_text("\n".join(L) + "\n")
L = ["% Generated by build_excess_extra.py (Nick, 2026-09-17) from starsim_excess_long.csv; do not edit by hand.",
     "% Starsim interventional excess CRPS / C_h by coverage and horizon; lower is better.",
     "\\setlength{\\tabcolsep}{3pt}", "\\begin{tabular}{lrrrrrrr}", "\\toprule",
     "Model & ECI & \\multicolumn{2}{c}{25\\% coverage} & \\multicolumn{2}{c}{50\\% coverage} & \\multicolumn{2}{c}{90\\% coverage} \\\\",
     "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}", " & & d40 & d60 & d40 & d60 & d40 & d60 \\\\", "\\midrule"]
for m in order:
    mid = m.openrouter_id; c = []
    for rung in ("c25", "c50", "c90"): c += [f3(cell("continuous", "interventional", rung, "40", mid)), f3(cell("continuous", "interventional", rung, "60", mid))]
    L.append(f"{name(m)} & {m.eci:.1f} & " + " & ".join(c) + " \\\\")
L += ["\\bottomrule", "\\end{tabular}"]; (OUT / "starsim_rung_horizon.tex").write_text("\n".join(L) + "\n")

# ---- horizon figure in raw units (people): excess CRPS minus floor, before dividing by C_h -----------------
fig, axes = plt.subplots(1, 3, figsize=(7.2, 2.4), sharey=True); fig.subplots_adjust(wspace=0.12); hstats = {}; YMAX = 600
for ax, rung in zip(axes, ("c25", "c50", "c90")):
    d40 = cells[("continuous", "interventional", rung, "40")]; d60 = cells[("continuous", "interventional", rung, "60")]
    ms = [m for m in d40 if d40[m]["complete"] and d60.get(m, {}).get("complete")]
    s40 = np.array([d40[m]["excess_raw"] for m in ms]); s60 = np.array([d60[m]["excess_raw"] for m in ms])
    for a, b in zip(s40, s60): ax.plot([40, 60], [a, b], color=fg.GREY, lw=0.5, alpha=0.7, zorder=1)
    q40 = np.percentile(s40, [25, 75]); q60 = np.percentile(s60, [25, 75])
    ax.fill_between([40, 60], [q40[0], q60[0]], [q40[1], q60[1]], color="#d9d9d9", alpha=0.6, zorder=0, lw=0)
    ax.plot([40, 60], [s40.mean(), s60.mean()], color=fg.GREEN, lw=2.2, marker="o", ms=4, zorder=3)
    ax.text(39.2, s40.mean(), f"{s40.mean():.0f}", ha="right", va="center", fontsize=6.5); ax.text(60.8, s60.mean(), f"{s60.mean():.0f}", ha="left", va="center", fontsize=6.5)
    ax.axhline(0, ls="--", lw=0.6, color=fg.GREY); ax.set_xticks([40, 60]); ax.set_xlim(36, 64); ax.set_ylim(-10, YMAX); ax.set_xlabel("Forecast horizon (day)"); ax.set_title(f"{rung[1:]}% coverage", fontsize=8)
    hstats[rung] = dict(mean40=float(s40.mean()), mean60=float(s60.mean()), median40=float(np.median(s40)), median60=float(np.median(s60)), worse_at_60=int((s60 > s40).sum()), n=len(ms), clipped=int(((s40 > YMAX) | (s60 > YMAX)).sum()))
axes[0].set_ylabel("Interventional excess CRPS\n(people; lower is better)")
axes[2].text(0.98, 0.0, "quantile oracle", transform=axes[2].get_yaxis_transform(), ha="right", va="bottom", fontsize=6, color=fg.GREY)
from matplotlib.lines import Line2D; from matplotlib.patches import Patch
axes[2].legend(handles=[Line2D([], [], color=fg.GREEN, lw=2.2, marker="o", ms=4, label="mean over models"), Patch(facecolor="#d9d9d9", label="interquartile range"), Line2D([], [], color=fg.GREY, lw=0.6, label="one model")], loc="upper right", fontsize=6, frameon=False)
fig.savefig(OUT / "fig_starsim_horizon.pdf", bbox_inches="tight"); fig.savefig(OUT / "fig_starsim_horizon.png", dpi=200, bbox_inches="tight"); plt.close(fig)
# pooled-over-rungs raw means and unconditional by horizon
pool = cells[("continuous", "interventional", "pooled(c25,c50,c90)", "40")], cells[("continuous", "interventional", "pooled(c25,c50,c90)", "60")]
ms = [m for m in pool[0] if pool[0][m]["complete"] and pool[1].get(m, {}).get("complete")]
hstats["pooled"] = dict(raw_mean40=float(np.mean([pool[0][m]["excess_raw"] for m in ms])), raw_mean60=float(np.mean([pool[1][m]["excess_raw"] for m in ms])),
                        raw_worse60=int(sum(pool[1][m]["excess_raw"] > pool[0][m]["excess_raw"] for m in ms)), norm_mean40=float(np.mean([pool[0][m]["excess"] for m in ms])), norm_mean60=float(np.mean([pool[1][m]["excess"] for m in ms])), n=len(ms))
u = cells[("continuous", "unconditional", "-", "40")], cells[("continuous", "unconditional", "-", "60")]
hstats["uncond"] = dict(raw_mean40=float(np.mean([u[0][m]["excess_raw"] for m in u[0]])), raw_mean60=float(np.mean([u[1][m]["excess_raw"] for m in u[1]])), raw_worse60=int(sum(u[1][m]["excess_raw"] > u[0][m]["excess_raw"] for m in u[0])), n=len(u[0]))
# per-set item difficulty (from per_item_table.json)
rec = json.load(open(OUT / "per_item_table.json")); diff = {}
for s in sorted({r["set"] for r in rec}):
    rs = [r for r in rec if r["set"] == s]; hardest = sorted(rs, key=lambda r: -r["excess_median"])[:4]
    diff[s] = dict(median_over_items=float(np.median([r["excess_median"] for r in rs])), hardest=[(r["item"], round(r["excess_median"], 2)) for r in hardest], easiest=min(rs, key=lambda r: r["excess_median"])["item"])
# binary and continuous distribution summaries for the results paragraph
b = [q[2] for q in pts("binary", "unconditional", "-") if q[3]]; c = [q[2] for q in pts("continuous", "unconditional", "-") if q[3]]
summ = dict(binary=dict(n_le_0_01=sum(v <= 0.01 for v in b), n_le_0_05=sum(v <= 0.05 for v in b), n_le_0_1=sum(v <= 0.1 for v in b), max=max(b), median=float(np.median(b)),
                        worst=[(fg.SHORT.get(q[0], q[0]), round(q[2], 2)) for q in sorted(pts("binary", "unconditional", "-"), key=lambda q: -q[2])[:4]]),
            continuous=dict(sorted=[round(v, 2) for v in sorted(c)], n_le_1=sum(v <= 1 for v in c), worst=[(fg.SHORT.get(q[0], q[0]), round(q[2], 2)) for q in sorted(pts("continuous", "unconditional", "-"), key=lambda q: -q[2])[:4]]),
            rungs={r: dict(mean=float(np.mean([q[2] for q in pts("continuous", "interventional", r) if q[3]])), all_below=float(max(q[2] for q in pts("continuous", "interventional", r) if q[3]))) for r in ("c25", "c50", "c90")},
            binc90=dict(neg=None, max=max(q[2] for q in pts("binary", "interventional", "c90") if q[3]), worst=[(fg.SHORT.get(q[0], q[0]), round(q[2], 2)) for q in sorted(pts("binary", "interventional", "c90"), key=lambda q: -q[2])[:3]], best=[(fg.SHORT.get(q[0], q[0]), round(q[2], 3)) for q in sorted(pts("binary", "interventional", "c90"), key=lambda q: q[2])[:2]]),
            hold=dict(max=max(q[2] for q in pts("binary", "interventional", "hold") if q[3]), worst=[(fg.SHORT.get(q[0], q[0]), round(q[2], 2)) for q in sorted([q for q in pts("binary", "interventional", "hold") if q[3]], key=lambda q: -q[2])[:3]], best=[(fg.SHORT.get(q[0], q[0]), round(q[2], 3)) for q in sorted([q for q in pts("binary", "interventional", "hold") if q[3]], key=lambda q: q[2])[:2]]),
            calls_cost=dict(calls=sum(int(r["n_calls"]) for r in long if r["horizon"] == "pooled" and not r["rung"].startswith("pooled")), cost=sum(r["cost_usd"] for r in long if r["horizon"] == "pooled" and not r["rung"].startswith("pooled"))))
json.dump(dict(validation=val, horizon_raw=hstats, difficulty=diff, summary=summ), open(OUT / "numbers_extra.json", "w"), indent=1, default=float)
print(json.dumps(dict(validation=val, horizon_raw=hstats, difficulty=diff, summary=summ), indent=0, default=float)); print("\n".join("\n".join(v) for v in snip.values()))
