#!/usr/bin/env python
"""The FreeCiv tables of Appendix C (full results).

Run from anywhere with a Python that has pandas, numpy and scipy:
    python data/freeciv/scripts/make_freeciv_tables.py

Outputs (bare tabulars, one per file, in data/appendix_tables/):
  freeciv_models.tex           per model: bank, tails, continuous, natural conditional, gain, parsed, cost
  freeciv_mirrors.tex          per model: mirrors excess Brier with 95% CI and by horizon
  freeciv_horizon_binary.tex   per model: bank excess Brier and tail bits by horizon
  freeciv_horizon_cont.tex     per model: continuous nCRPS and natcond excess_t2 by horizon
  freeciv_natcond_blocks.tex   per model: natcond excess_t2 and gain by structural block
and data/freeciv/freeciv_numbers.json: every number quoted in the appendix prose, with its source.

Sources (data/freeciv/): freeciv_results_wide.csv, SCORES.md, score_items.csv.gz, model_scores.csv.
Every value is cross-checked between the wide file, SCORES.md and the per-item rows before it is written.

This is the FreeCiv part of the retired data/make_appendix_tables.py (2026-09-16).  The Micropolis and
StarSim tables that script also wrote are now generated by Fabio's analyze_paper.py and by
data/starsim/scripts/, and are never written here.
"""
import json
import re
from datetime import date

import numpy as np
import pandas as pd

from _common import (DATA, REPO, RUN, SCORES_MD, SCORE_ITEMS, TABLES, WIDE, fmt, load_capability, load_items,
                     load_wide, models_by_eci, name, parse_md_tables, spearman_signed, write_tabular, rel)

TABLES.mkdir(parents=True, exist_ok=True)
NUMBERS = {"generated": str(date.today()), "script": "data/freeciv/scripts/make_freeciv_tables.py",
           "sources": {"wide": rel(WIDE), "scores_md": rel(SCORES_MD),
                       "score_items": rel(SCORE_ITEMS)}}

cap = load_capability()
fw = load_wide()
fc_models = models_by_eci(fw)
assert len(fc_models) == 24 and set(fc_models) == set(cap.index)
for m in fc_models:
    assert abs(fw.loc[m, "eci"] - cap.loc[m, "eci"]) < 1e-6, m
scores = parse_md_tables(SCORES_MD.read_text())
items = load_items()
FT = [90, 120, 150, 180, 210]
FT_NC = [120, 150, 180, 210]

# ---------------------------------------------------------------- per-model headline table
rows, f_rec = [], {}
for m in fc_models:
    vals = [fw.loc[m, c] for c in ["bank_all_excess_brier", "tails_all_excess_bits", "continuous_all_ncrps_global",
                                   "continuous_all_excess_ncrps_global", "natcond_all_excess_t2", "natcond_all_gain"]]
    n_items = sum(fw.loc[m, f"{s}_all_n_items"] for s in ["bank", "tails", "mirrors", "continuous", "natcond"])
    n_valid = sum(fw.loc[m, f"{s}_all_n_valid"] for s in ["bank", "tails", "mirrors", "continuous", "natcond"])
    cost = float(fw.loc[m, "total_cost_usd"])
    rows.append([name(m), f"{fw.loc[m, 'eci']:.1f}", fmt(vals[0], 4), fmt(vals[1], 3), fmt(vals[2], 3), fmt(vals[3], 3),
                 fmt(vals[4], 4), fmt(vals[5], 4), fmt(n_valid / n_items, 1, pct=True), f"{cost:.2f}"])
    f_rec[m] = dict(eci=float(fw.loc[m, "eci"]), bank_excess_brier=float(vals[0]), tails_excess_bits=float(vals[1]),
                    continuous_ncrps_global=float(vals[2]), continuous_excess_ncrps_global=float(vals[3]),
                    natcond_excess_t2=float(vals[4]), natcond_gain=float(vals[5]), parsed_share=float(n_valid / n_items),
                    n_items_five_sets=int(n_items), total_calls=int(fw.loc[m, "total_calls"]), cost_usd=cost)
write_tabular(TABLES / "freeciv_models.tex", "lrrrrrrrrr",
              ["Model & ECI & Mid-range & Tails & \\multicolumn{2}{c}{Continuous} & \\multicolumn{2}{c}{Natural conditional} & Parsed & Cost",
               "\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}",
               " & & excess Brier & bits & nCRPS & excess & excess Brier & gain & (\\%) & (\\$)"],
              rows, comment=("FreeCiv per model (provisional, one question per prompt). Source: " if RUN.startswith("run1") else "FreeCiv per model (run 2: batched at up to 50 binary / 20 continuous questions per prompt; natural conditionals one per prompt). Source: ") + " freeciv_results_wide.csv, columns "
                            "bank_all_excess_brier, tails_all_excess_bits, continuous_all_ncrps_global, continuous_all_excess_ncrps_global, "
                            "natcond_all_excess_t2, natcond_all_gain, *_all_n_valid / *_all_n_items over the five scored sets, total_cost_usd.")
NUMBERS["freeciv"] = {"per_model": f_rec, "n_models": 24, "total_cost_usd": float(fw["total_cost_usd"].sum()),
                      "parsed_share_range": [min(r["parsed_share"] for r in f_rec.values()), max(r["parsed_share"] for r in f_rec.values())],
                      "gain_positive_models": int(sum(r["natcond_gain"] > 0 for r in f_rec.values())),
                      "gain_mean": float(np.mean([r["natcond_gain"] for r in f_rec.values()])),
                      "gain_range": [min(r["natcond_gain"] for r in f_rec.values()), max(r["natcond_gain"] for r in f_rec.values())]}

# ---------------------------------------------------------------- mirrors
mir_md = scores["Mirrors 50 — excess Brier"].set_index("model")
mir_h = scores["mirrors: excess_brier by horizon"].set_index("model")
assert len(mir_md) == 24 and len(mir_h) == 24
mi = items[items["set"] == "mirrors"]
one = mi.drop_duplicates("item")
assert len(one) == 50 and one.q.min() >= 0.95 and one.q.max() < 1
per_h_count = one.groupby("T").size().to_dict()
assert all(v == 10 for v in per_h_count.values()) and sorted(per_h_count) == FT
flat05 = float(((0.5 - one.q) ** 2).mean())
rows, m_rec = [], {}
for m in fc_models:
    est = float(mir_md.loc[m, "excess_brier"])
    ci = mir_md.loc[m, "95% CI"]
    assert abs(est - fw.loc[m, "mirrors_all_excess_brier"]) < 6e-5, (m, est, fw.loc[m, "mirrors_all_excess_brier"])
    assert abs(est - mi[mi.model == m].excess_brier.mean()) < 6e-5, m
    byh = [float(mir_h.loc[m, f"T{t}"]) for t in FT]
    for t, v in zip(FT, byh):
        assert abs(v - fw.loc[m, f"mirrors_{t}_excess_brier"]) < 6e-5, (m, t)
    lo, hi = [float(x) for x in re.findall(r"[-0-9.]+", ci)]
    rows.append([name(m), f"{fw.loc[m, 'eci']:.1f}", fmt(est, 4), f"[{lo:.3f}, {hi:.3f}]"] + [fmt(v, 3) for v in byh])
    m_rec[m] = dict(excess_brier=est, ci95=[lo, hi], by_horizon=dict(zip([str(t) for t in FT], byh)))
write_tabular(TABLES / "freeciv_mirrors.tex", "lrrlrrrrr",
              ["Model & ECI & Excess Brier & 95\\% CI & \\multicolumn{5}{c}{By horizon (turn)}",
               "\\cmidrule(lr){5-9}",
               " & & & & 90 & 120 & 150 & 180 & 210"],
              rows, comment="FreeCiv mirrors set (50 binary questions with 0.95 <= q < 1, 10 per horizon). Source: SCORES.md "
                            "(sections 'Mirrors 50' and 'mirrors: excess_brier by horizon'), cross-checked against freeciv_results_wide.csv "
                            "and score_items.csv. The 95% CI is the item-level interval printed in SCORES.md (bootstrap over items).")
beat = [m for m in fc_models if m_rec[m]["excess_brier"] < flat05]
rho_m, p_m, ci_m, nb = spearman_signed([fw.loc[m, "eci"] for m in fc_models], [m_rec[m]["excess_brier"] for m in fc_models])
NUMBERS["freeciv"]["mirrors"] = {
    "n_items": 50, "per_horizon": 10, "q_min": float(one.q.min()), "q_max": float(one.q.max()), "q_mean": float(one.q.mean()),
    "flat_0p5_excess": flat05, "models_below_flat_0p5": beat, "n_below_flat_0p5": len(beat),
    "within_0p0005_of_flat": [m for m in fc_models if abs(m_rec[m]["excess_brier"] - flat05) < 5e-4 and m not in beat],
    "best": min(m_rec, key=lambda m: m_rec[m]["excess_brier"]), "worst": max(m_rec, key=lambda m: m_rec[m]["excess_brier"]),
    "spearman_vs_eci_signed": rho_m, "p": p_m, "ci95_models_boot": ci_m, "n_boot_valid": nb, "per_model": m_rec,
    "family_horizon_source": "COMPOSITION.md"}

# ---------------------------------------------------------------- by horizon
bank_h = scores["bank: excess_brier by horizon"].set_index("model")
tails_h = scores["tails: excess_bits by horizon"].set_index("model")
cont_h = scores["continuous: ncrps_global by horizon"].set_index("model")
nc_h = scores["natcond: excess_t2 by horizon"].set_index("model")
rows, rows2, hb_rec = [], [], {}
for m in fc_models:
    b = [float(fw.loc[m, f"bank_{t}_excess_brier"]) for t in FT]
    t_ = [float(fw.loc[m, f"tails_{t}_excess_bits"]) for t in FT]
    c = [float(fw.loc[m, f"continuous_{t}_ncrps_global"]) for t in FT]
    n = [float(fw.loc[m, f"natcond_{t}_excess_t2"]) for t in FT_NC]
    for t, v in zip(FT, b):
        assert abs(v - float(bank_h.loc[m, f"T{t}"])) < 6e-5
    for t, v in zip(FT, t_):
        assert abs(v - float(tails_h.loc[m, f"T{t}"])) < 6e-5
    for t, v in zip(FT, c):
        assert abs(v - float(cont_h.loc[m, f"T{t}"])) < 6e-5
    for t, v in zip(FT_NC, n):
        assert abs(v - float(nc_h.loc[m, f"T{t}"])) < 6e-5
    for t in FT:
        assert fw.loc[m, f"bank_{t}_n_items"] == 150 and fw.loc[m, f"tails_{t}_n_items"] == 60 and fw.loc[m, f"continuous_{t}_n_items"] == 60
    for t in FT_NC:
        assert fw.loc[m, f"natcond_{t}_n_items"] == 100
    rows.append([name(m), f"{fw.loc[m, 'eci']:.1f}"] + [fmt(v, 4) for v in b] + [fmt(v, 3) for v in t_])
    rows2.append([name(m), f"{fw.loc[m, 'eci']:.1f}"] + [fmt(v, 3) for v in c] + [fmt(v, 4) for v in n])
    hb_rec[m] = dict(bank=dict(zip(map(str, FT), b)), tails=dict(zip(map(str, FT), t_)),
                     continuous=dict(zip(map(str, FT), c)), natcond=dict(zip(map(str, FT_NC), n)))
write_tabular(TABLES / "freeciv_horizon_binary.tex", "lrrrrrrrrrrr",
              ["Model & ECI & \\multicolumn{5}{c}{Mid-range excess Brier, by horizon (turn)} & \\multicolumn{5}{c}{Tail excess bits, by horizon (turn)}",
               "\\cmidrule(lr){3-7}\\cmidrule(lr){8-12}",
               " & & 90 & 120 & 150 & 180 & 210 & 90 & 120 & 150 & 180 & 210"],
              rows, comment="FreeCiv mid-range set (150 questions per horizon) and tails (60 per horizon) by resolution turn. Source: "
                            "freeciv_results_wide.csv, columns bank_{T}_excess_brier and tails_{T}_excess_bits; cross-checked against SCORES.md.")
write_tabular(TABLES / "freeciv_horizon_cont.tex", "lrrrrrrrrrr",
              ["Model & ECI & \\multicolumn{5}{c}{Continuous nCRPS, by horizon (turn)} & \\multicolumn{4}{c}{Natural-conditional excess Brier}",
               "\\cmidrule(lr){3-7}\\cmidrule(lr){8-11}",
               " & & 90 & 120 & 150 & 180 & 210 & 120 & 150 & 180 & 210"],
              rows2, comment="FreeCiv continuous (60 questions per horizon) and natural conditionals (100 cells per horizon, turn-2 excess "
                             "Brier against p(Y|X)) by resolution turn. Source: freeciv_results_wide.csv, columns continuous_{T}_ncrps_global "
                             "and natcond_{T}_excess_t2; cross-checked against SCORES.md.")
NUMBERS["freeciv"]["by_horizon"] = hb_rec
NUMBERS["freeciv"]["mean_by_horizon"] = {k: {t: float(np.mean([hb_rec[m][k][t] for m in fc_models])) for t in hb_rec[fc_models[0]][k]}
                                         for k in ["bank", "tails", "continuous", "natcond"]}

# ---------------------------------------------------------------- natcond by structural block
blk_md = scores["natcond by block (excess_t2 / stay / gain / excess_nonews)"].set_index("model")
BLOCKS = ["A", "B", "C1", "C2", "D"]
nci = items[items["set"] == "natcond"]
blk_n = nci.drop_duplicates("item").groupby("block").size().to_dict()
assert blk_n == {"A": 36, "B": 36, "C1": 56, "C2": 172, "D": 100}, blk_n
rows, blk_rec = [], {}
for m in fc_models:
    ex, ga = [], []
    for b in BLOCKS:
        parts = [float(x) for x in blk_md.loc[m, b].split("/")]
        sub = nci[(nci.model == m) & (nci.block == b)]
        ex_i, ga_i = float(sub.excess_t2.mean()), float(sub.gain.mean())
        assert abs(ex_i - parts[0]) < 6e-4 and abs(ga_i - parts[2]) < 6e-4, (m, b, parts, ex_i, ga_i)
        ex.append(ex_i)
        ga.append(ga_i)
    rows.append([name(m), f"{fw.loc[m, 'eci']:.1f}"] + [fmt(v, 3) for v in ex] + [fmt(v, 3) for v in ga])
    blk_rec[m] = dict(excess_t2=dict(zip(BLOCKS, ex)), gain=dict(zip(BLOCKS, ga)))
write_tabular(TABLES / "freeciv_natcond_blocks.tex", "lrrrrrrrrrrr",
              ["Model & ECI & \\multicolumn{5}{c}{Turn-2 excess Brier, by block} & \\multicolumn{5}{c}{Gain over not updating, by block}",
               "\\cmidrule(lr){3-7}\\cmidrule(lr){8-12}",
               " & & A & B & C1 & C2 & D & A & B & C1 & C2 & D"],
              rows, comment="FreeCiv natural conditionals by structural block (A irrelevant 36 cells, B related weak 36, C1 mechanical "
                            "same-series 56, C2 persistence across series 172, D inferential 100). Source: score_items.csv (set natcond, "
                            "columns excess_t2 and gain, mean over cells per model and block), cross-checked against SCORES.md 'natcond by block'.")
NUMBERS["freeciv"]["natcond_blocks"] = {
    "cells_per_block": blk_n, "per_model": blk_rec,
    "gain_negative_count_by_block": {b: int(sum(blk_rec[m]["gain"][b] < 0 for m in fc_models)) for b in BLOCKS},
    "gain_mean_by_block": {b: float(np.mean([blk_rec[m]["gain"][b] for m in fc_models])) for b in BLOCKS}}

(DATA / "freeciv_numbers.json").write_text(json.dumps(NUMBERS, indent=1, default=float))
print("wrote", rel(DATA / "freeciv_numbers.json"))
